### ISSUE TITLE
Transition not working...

### ISSUE THREAD

**Issue by axel578** [visioforge/.Net-SDK-s-samples-before-v12#1]
one year ago I had the same problem with it , never resolved , your transition does'nt work , even with the code that you propose in your tutorial or in the forum , the issue is from your library , sorry , if the problem is not resolved , i may never buy it , too big issue ...

**Comment by visioforge** [comment]
Hi axel578,

Could you show me problem code?

Sincerely,
Roman Minyaylov
VisioForge support

---

Gitter community chat - https://gitter.im/visioforge/Lobby#

---
To rate this answer or view ticket history please follow the link:
https://support.visioforge.com/ticket_529i6Fs4RNjw3I2J

**Comment by axel578** [comment]
here is my code where the transition doesn't work ( the video file + audio file ) have correct length :


            VFVEVideoSource videoFile = new VFVEVideoSource("video/001.mp4", new[] { new VFVEFileSegment(0, 41000) });
            VFVEAudioSource audioFile = new VFVEAudioSource("video/001.mp4", new[] { new VFVEFileSegment(0, 41000) });

           
            ve.Input_AddVideoFile(videoFile, -1);
            //ve.FastEdit_JoinFiles(file_join, "video/googl.wmv");
            ve.Input_AddAudioFile(audioFile, -1);
            ve.Video_FrameRate = 25;
            ve.Video_Resize_Width = 1280;
            ve.Video_Resize_Height = 720;
            ve.Output_Format = new VFWMVOutput();
            ve.Input_AddImageFile("images/001.png", 40000, -1, VFVideoEditStretchMode.Letterbox, 0, 1280, 720);
            ve.Video_Transition_Add(40000,41000, 12);
            ve.Video_Effects_Enabled = true;
            ve.Video_Renderer = new VideoRendererSettingsBase
            {
                VideoRendererInternal = VFVideoRendererInternal.None,
                StretchMode = VFVideoRendererStretchMode.Letterbox
            };
            ve.Output_Filename = "video/final.wmv";
            ve.OnProgress += (sender, e) =>
            {
                Console.Out.WriteLine("Video Encoding Status : " + e.Progress);
            };

            ve.OnStop += (sender, e) =>
            {
                Console.Out.WriteLine("Done. Please press any key.");
            };

            ve.OnError += (sender, e) =>
            {
                Console.Out.WriteLine("Error: " + e.Message + "\n" + e.StackTrace + "\n" + e.CallSite);
            };

            ve.ConsoleUsage = true;

            ve.Start();

**Comment by axel578** [comment]
ha and that also before all that code :
VisioForge.Controls.VideoEdit.VideoEditCore ve = new VisioForge.Controls.VideoEdit.VideoEditCore();

**Comment by axel578** [comment]
correction its this line : ve.Input_AddImageFile("images/001.png", 2000, 40000, VFVideoEditStretchMode.Letterbox, 0, 1280, 720);

**Comment by axel578** [comment]
but it still doesnt work
