### ISSUE TITLE
Global video problem

### ISSUE THREAD

**Issue by axel578** [visioforge/.Net-SDK-s-samples-before-v12#2]
I tried a bunch of ways to repare the issue , installed last version uninstalled it by deleting all the registery keys associated to it and reinstalled , installed it from nuget , still doesn't work 👍 

IRenderEngine.ConnectFrontEnd => DESErrorLogCB.LogError => VideoEditCore.y5tBovVhX
VisioForge.Controls.VideoEdit.VideoEditCore.y5tBovVhX
Error: GetGroupOutputPin: Operation failed because project was not rendered successfully.
VideoEditCore.Start => VideoEditCore.mkHvKFqme => VideoEditCore.GJCOvPn3c
VisioForge.Controls.VideoEdit.VideoEditCore.GJCOvPn3c
Error: GetGroupOutputPin: Operation failed because project was not rendered successfully.
VideoEditCore.Start => VideoEditCore.mkHvKFqme => VideoEditCore.GJCOvPn3c
VisioForge.Controls.VideoEdit.VideoEditCore.GJCOvPn3c
Error: GetGroupOutputPin: Operation failed because project was not rendered successfully.
VideoEditCore.Start => VideoEditCore.mkHvKFqme => VideoEditCore.zcdqaQ5idU8TxTgiHwd
VisioForge.Controls.VideoEdit.VideoEditCore.zcdqaQ5idU8TxTgiHwd
Error: GetGroupOutputPin: Operation failed because project was not rendered successfully.
VideoEditCore.Start => VideoEditCore.mkHvKFqme => VideoEditCore.zcdqaQ5idU8TxTgiHwd
VisioForge.Controls.VideoEdit.VideoEditCore.zcdqaQ5idU8TxTgiHwd
Error: La référence d'objet n'est pas définie à une instance d'un objet.
Program.Main => VideoEditCore.Start => VideoEditCore.mkHvKFqme
VisioForge.Controls.VideoEdit.VideoEditCore.mkHvKFqme
Error: Unable to start: IMediaControl.Run is null
VideoEditCore.mkHvKFqme => VideoEditCore.QxaY0SryC => VideoEditCore.zcdqaQ5idU8TxTgiHwd
VisioForge.Controls.VideoEdit.VideoEditCore.zcdqaQ5idU8TxTgiHwd

**Comment by roman-miniailov** [comment]
Please send logs - https://support.visioforge.com/041973-How-to-send-debug-info
