### ISSUE TITLE
MediaPlayer SDK - after set speed not working as expcected 

### ISSUE THREAD

**Issue by Zeleksonob** [visioforge/.Net-SDK-s-samples-before-v12#3]
after using setspeed() on the media player, the event OnVideoFrameBitmap return the right frame but not the right start time (start time value is a I never set the set speed)

**Comment by visioforge** [comment]
Hi

Start time of the frame is playback speed are not related values. With higher than 100% playback speed you'll receive frames more often, but with original start time value.

**Comment by visioforge** [comment]
Hi 

Start time of the frame is playback speed are not related values. With higher than 100% playback speed you'll receive frames more often, but with original start time value.

Sincerely,
Roman Minyaylov
VisioForge support

---

Gitter community chat - https://gitter.im/visioforge/Lobby#

---
To rate this answer or view ticket history please follow the link:
https://support.visioforge.com/ticket_IwfIFQ7y7ozeP6i1

**Comment by Zeleksonob** [comment]
ok thank you
