### ISSUE TITLE
playing mpg video file gives error (while all other players in windows playing this file normally

### ISSUE THREAD

**Issue by Zeleksonob** [visioforge/.Net-SDK-s-samples-before-v12#4]
Hi, using also the demo you provided  playing mpg, mp4,WMV file not working  while in other windows player it's working  the error given is : 

**Unable to get video card video processing ranges: -1072875854.**

remark: my graphic card is GeForce 1080 and updated to the latest version

**Comment by visioforge** [comment]
Hi

Please send logs - https://support.visioforge.com/041973-How-to-send-debug-info

**Comment by visioforge** [comment]
Hi 

Please send logs - https://support.visioforge.com/041973-How-to-send-debug-info

Sincerely,
Roman Minyaylov
VisioForge support

---

Gitter community chat - https://gitter.im/visioforge/Lobby#

---
To rate this answer or view ticket history please follow the link:
https://support.visioforge.com/ticket_W181oIh4537U1dM5

**Comment by Zeleksonob** [comment]
DEBUG | 2019/09/22 11:54:34.754 | VisioForge.Controls.MediaPlayer.MediaPlayerCore.VXWvTvBn5p3Yc1eRUb3 | DirectShow event: Complete
ERROR | 2019/09/24 10:45:14.377 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 10:45:14.403 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 10:45:14.403 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 10:45:14.403 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:15.702 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:15.702 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:15.713 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:15.713 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:21.241 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:21.244 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:21.244 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
ERROR | 2019/09/24 11:19:21.244 | VisioForge.MediaFramework.Classes.DSScreenRenderer.gmf7bw9pnr6SZfaRfMIM | Unable to get video card video processing ranges: -1072875854.
DEBUG | 2019/09/24 11:19:27.657 | VisioForge.Controls.MediaPlayer.MediaPlayerCore.rNUAeQB6thZbCwHNJMx | COM object that has been separated from its underlying RCW cannot be used.

**Comment by Zeleksonob** [comment]
[debug_log.txt](https://github.com/visioforge/.Net-SDK-s-samples/files/3646046/debug_log.txt)

**Comment by visioforge** [comment]
Please share all log files in one zip.

**Comment by Zeleksonob** [comment]
[VisioForge.zip](https://github.com/visioforge/.Net-SDK-s-samples/files/3646090/VisioForge.zip)

**Comment by visioforge** [comment]
Try to change playback engine to LAV and video renderer to VMR-9.

**Comment by Zeleksonob** [comment]
using lav filter in your demo throwes accsees violation exception, when reaching to MediaPlayer.play()

**Comment by visioforge** [comment]
OK, try to change video renderer to VMR-9.

**Comment by Zeleksonob** [comment]
[VisioForge.zip](https://github.com/visioforge/.Net-SDK-s-samples/files/3646233/VisioForge.zip)
 
gives me a different error now

**Comment by visioforge** [comment]
Please update SDK to v11 to resolve this issues.

**Comment by Zeleksonob** [comment]
i use the 10 version yes, but before I will renew my license, how I can be sure that v11 gonna fix my problem?

**Comment by roman-miniailov** [comment]
You can use trial version to test.

Also if your purchase was less than 1 year ago you can upgrade to v11 for free.

**Comment by visioforge** [comment]
Please update SDK to v11 to resolve this issues.
