### ISSUE TITLE
How to transition from one video to another in media player sdk?

### ISSUE THREAD

**Issue by hrueger** [visioforge/.Net-SDK-s-samples-before-v12#5]
I would like to have a fluid transition from one video to another. This must be dynamic, so that I can change to another video while a different video is running. How can I do this?
I can't add all Videos as PIP Sources at the beginning, because when I transition to a video, this should start from the beginning and not in the middle. Or can I seek to a certain time in a PIP Video Source?

**Comment by roman-miniailov** [comment]
Unfortunately, you can't do it using Media Player SDK. Using Video Edit SDK you can add several videos with transitions between them.
