### ISSUE TITLE
net sdk. .wmv videos files - video speed not working 

### ISSUE THREAD

**Issue by Zeleksonob** [visioforge/.Net-SDK-s-samples-before-v12#6]
Hi, I'm using the latest version for c#,

the player speed is not working in any WMV video format.

no change to the video no matter what the speed factor I'm using, the video always stays at normal speed (1)

**Comment by roman-miniailov** [comment]
About ASF playback speed - https://docs.microsoft.com/en-us/windows/win32/wmformat/reading-asf-files-in-directshow

Using DirectShow (File_DS) engine it's not possible to control playback speed.

Using LAV engine it's possible to control speed, but that not officially supported engine and can cause seeking problems for some WMV and ASF files.

**Comment by Zeleksonob** [comment]
Roman, thanks for the fast answer :)
