### ISSUE TITLE
How to parse startTime on OnVideoFrameBuffer to time code format 

### ISSUE THREAD

**Issue by videoInform** [visioforge/.Net-SDK-s-samples-before-v12#7]
Hi,
I'm using MediaPlayerCore class and register to the OnVideoFrameBuffer event, 
in this event there start time long prop, 
how can I parse it to a time code format  (hh:mm:ss:frame)?

**Comment by visioforge** [comment]
In SDK v12 BETA (I can share a link) we using TimeSpan instead long as a timestamp. 
In v11 "long" is time in milliseconds.

No frame number in event args, but you can use simple counter.
