### ISSUE TITLE
Video Resize missing from v11?

### ISSUE THREAD

**Issue by appindus-ibiller** [visioforge/.Net-SDK-s-samples-before-v12#8]
Hi,
We own both v7 and v11 licenses, and when porting older code from 7 to 11, we noticed that the Video_Resize_Mode settings (Video_ResizeOrCrop_Enabled, Video_Crop_Bottom, Top, Left, Right, Video_Resize_NewHeight, Width, are all gone)

There is a Video_Resize, and a Video_Resize.Mode, but they don't seem to do what the old code used to.

Is there a way to do this in v11 that maybe we're not seeing? If not, has this feature returned in a newer version?

Thank you for any help you can provide!

**Comment by visioforge** [comment]
Current SDK version is 14. You can use Video_Resize property and corresponding class to configure video resize.
